# Generated by Django 5.0.4 on 2025-04-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_mapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='depth',
            field=models.IntegerField(default=0, help_text='Click depth level from starting URL'),
        ),
        migrations.AddField(
            model_name='sitemapjob',
            name='current_depth',
            field=models.IntegerField(default=0, help_text='Current click depth being processed'),
        ),
        migrations.AddField(
            model_name='sitemapjob',
            name='max_depth',
            field=models.IntegerField(default=3, help_text='Maximum click depth to process'),
        ),
    ]
