# Generated by Django 5.0.4 on 2025-04-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_mapper', '0002_link_depth_sitemapjob_current_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='site_mapper.sitemapjob'),
        ),
    ]
